---

- hosts: all, !platforma
  gather_facts: true
  strategy: linear
  become: yes

  roles:

    - role: docker-compose-run
      docker_compose_run_local_common_services_dir: "./services"
      docker_compose_run_remote_services_dir: "/opt/services/monitoring"
      docker_compose_run_transfer_images: false
      docker_compose_run_action: present
      docker_compose_run_services_list:
        - consul-client
        - fluent-bit
        - node-exporter
        - cadvisor