auth_enabled: false

analytics:
  reporting_enabled: false

server:
  http_listen_port: 3100
  grpc_server_max_recv_msg_size: 52428800
  grpc_server_max_send_msg_size: 52428800
  http_server_read_timeout: 10m
  http_server_write_timeout: 10m

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 5m

limits_config:
  ingestion_rate_mb: 20
  ingestion_burst_size_mb: 20
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: {{ inventory_reject }}

chunk_store_config:
  max_look_back_period: {{ inventory_retention }}
table_manager:
  retention_deletes_enabled: true
  retention_period: {{ inventory_retention }}

ruler:
  external_url: https://monitoring.net-vision.pro/grafana/explore
#  external_labels:
#    project: {{ inventory_project_name }}
  alertmanager_url: http://monitoring-alertmanager:9093
  enable_api: true
  enable_alertmanager_v2: true