version: '3.7'

services:

  {{ inventory_fluentbit_hostname }}:
    image: fluent/fluent-bit:{{ inventory_fluentbit_tag }}
    hostname: {{ inventory_fluentbit_hostname }}
    container_name: {{ inventory_fluentbit_hostname }}
    user: root
    volumes:
      - ./config/:/fluent-bit/etc/
      - /var/log/:/fluent-bit/etc/logs/:ro
      - {{ fluentbit_log_path }}:/fluent-bit/etc/docker/
    restart: always
    ports:
      - 2020:2020
    networks:
      - {{ inventory_monitoring_network }}
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"
    healthcheck:
      test: curl -s http://127.0.0.1:2020/api/v1/health | grep -q "ok" || kill 1
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  {{ inventory_monitoring_network }}:
    name: {{ inventory_monitoring_network }}
    external: true

