apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://monitoring-prometheus:9090
    basicAuth: false
    isDefault: true
    editable: false
    version: 1
    jsonData:
       graphiteVersion: "1.1"
       tlsAuth: false
       tlsAuthWithCACert: false

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://monitoring-loki:3100
    basicAuth: false
    isDefault: false
    editable: false