version: "3.7"

services:

  {{ inventory_loki_hostname }}:
    image: grafana/loki:{{ inventory_loki_tag }}
    hostname: {{ inventory_loki_hostname }}
    container_name: {{ inventory_loki_hostname }}
    networks:
      - {{ inventory_monitoring_network }}
    ports:
      - {{ project_external_ip }}:{{ inventory_loki_port }}:3100
    volumes:
      - ./config/config.yml:/loki/config.yml
      - ./config/rules.yml:/loki/rules/fake/rules.yml
      - loki-data:/loki
    command:
      - -config.file=/loki/config.yml
      - -log.level=warn
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "5"

networks:
  {{ inventory_monitoring_network }}:
    name: {{ inventory_monitoring_network }}
    external: true

volumes:
  loki-data:
